# Generated by Django 5.1.6 on 2025-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_address',
            field=models.CharField(default='Address', max_length=200),
        ),
    ]
